### ISSUE TITLE
XSS attack possible through authorizationUri or oauth2 auth method

### ISSUE THREAD

**Issue by jarrodek** [advanced-rest-client/auth-methods#17]
```yaml
#%RAML 1.0
title: New API
securitySchemes:
  SecurityScheme:
    type: OAuth 2.0
    settings:
      authorizationUri: javascript:alert(document.domain);//
baseUri: http://example.com
/stored_xss:
  get:
    body: {}
    securedBy:
      - SecurityScheme
```

When requesting for a token it is possible to execute JS code instead of making OAth request. The component should validate URL input for URIs.
