### ISSUE TITLE
Ensure authorizationUri is valid URI

### ISSUE THREAD

**Issue by jarrodek** [advanced-rest-client/auth-methods#18]
```yaml
#%RAML 1.0
title: New API
securitySchemes:
  SecurityScheme:
    type: OAuth 2.0
    settings:
      authorizationUri: non-uri
baseUri: http://example.com
/stored_xss:
  get:
    body: {}
    securedBy:
      - SecurityScheme
```
In this API the `authorizationUri` is invalid but the component still render is as valid. The authorisation component won't be able to handle this anyway. The element should test for input and:
- render error message when input is invalid (keep the input in the text field)
- disable token request when the input is invalid
- ignore storing the URI in local storage when input is not valid URI
